apiVersion: v1
kind: Namespace
metadata:
  name: test

---

apiVersion: v1
kind: Secret
metadata:
  name: harborsecret
  namespace: test
data:
  .dockerconfigjson: "data"
type: kubernetes.io/dockerconfigjson

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellonode
  namespace: test
  labels:
    app: hellonode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hellonode
  template:
    metadata:
      labels:
        app: hellonode
    spec:
      imagePullSecrets:
        - name: harborsecret
      containers:
      - name: hellonode
        image: harbor.localdomain/mytest/hellonode:latest
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.2"
          limits:
            memory: "256Mi"
            cpu: "0.5"

---

apiVersion: v1
kind: Service
metadata:
  name: hellonode
  namespace: test
spec:
  selector:
    app: hellonode
  type: LoadBalancer 
  ports:
  - protocol: TCP
    port: 8000 #Service port
    targetPort: 8000 #The port for the hellonode application container
