{{- if .Values.imageCredentials.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "registrySecret" . }}
  labels:
    {{- include "hellonode.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.dockerConfigJson.data }}
{{- end -}}
