name: Manually Triggered Workflow
on:
#  push:
#    branches:
#      - main
  workflow_dispatch:
    #inputs:
    #  logLevel:
    #    description: 'Log level'
    #    required: false
    #    default: 'warning'
    #  environment:
    #    description: 'Environment to deploy'
    #    required: false
    #    default: 'staging'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Temporary Token
        run: |
          TOKEN_RESPONSE=$(curl --location "${{ secrets.CORTEX_API_URL }}/public_api/v1/unified-cli/image/token" \
            --header "Authorization: ${{ secrets.CORTEX_API_KEY }}" \
            --header "x-xdr-auth-id: ${{ secrets.CORTEX_API_KEY_ID }}" \
            --header 'Content-Type: application/json' \
            --data '{}')
          TEMP_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.token')
          echo "TEMP_TOKEN=$TEMP_TOKEN" >> $GITHUB_ENV

      - name: Pull Scanner Image
        run: |
          docker pull distributions.traps.paloaltonetworks.com/cli-docker/${{env.TEMP_TOKEN}}/method:amd64-${{ secrets.CORTEX_CLI_VERSION }}
          docker tag distributions.traps.paloaltonetworks.com/cli-docker/${{env.TEMP_TOKEN}}/method:amd64-${{ secrets.CORTEX_CLI_VERSION }} cortexcli:${{ secrets.CORTEX_CLI_VERSION }}

      - name: Scan Code
        run: |
          docker run --rm -v ${{ github.workspace }}:/home/code cortexcli:${{ secrets.CORTEX_CLI_VERSION }} \
            --api-base-url ${{ secrets.CORTEX_API_URL }} \
            --api-key ${{ secrets.CORTEX_API_KEY }} \
            --api-key-id ${{ secrets.CORTEX_API_KEY_ID }} \
            code scan \
            --directory /home/code \
            --repo-id ${{github.repository}} \
            --branch ${{github.ref_name}} \
            --source 'GITHUB_ACTIONS' \
            --create-repo-if-missing

      - name: Build Application Image
        run: docker build -t "${{ secrets.GAR_PREFIX }}/${{ secrets.GCP_PROJECT }}/${{ github.repository }}:${{ github.run_number }}" .
        # run: docker build -t "quay.io/mmurhamm/${{ github.repository }}:${{ github.run_number }}" .

      - name: Test Application Image
        run: echo "Tests passed."

      - name: Scan Application Image
        run: echo "Image scanner currently not working ..."
        #run: |
        #  docker run --rm -v ${{ github.workspace }}:/home/code cortexcli:${{ secrets.CORTEX_CLI_VERSION }} \
        #    --api-base-url ${{ secrets.CORTEX_API_URL }} \
        #    --api-key ${{ secrets.CORTEX_API_KEY }} \
        #    --api-key-id ${{ secrets.CORTEX_API_KEY_ID }} \
        #    image scan ${{ secrets.GAR_PREFIX }}/${{ secrets.GCP_PROJECT }}/${{ github.repository }}:${{ github.run_number }} \
        #    --ci-pipeline-id ${{ github.workflow }} \
        #    --ci-build-id ${{ github.run_number }} \
        #    --name /home/code/${{ github.repository }}.${{ github.run_number }} \
        #    --output-format json \
        #    --timeout 240

      #- name: Archive Scan Results
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: image-scan-report
      #    path: ${{ github.repository }}.${{ github.run_number }}
      #    retention-days: 20                                                # 90 is the default          

      - name: Generate Application Image SBOM
        run: echo "Image scanner currently not working ..."
        #run: |
        #  docker run --rm -v ${{ github.workspace }}:/home/code cortexcli:${{ secrets.CORTEX_CLI_VERSION }} \
        #    --api-base-url ${{ secrets.CORTEX_API_URL }} \
        #    --api-key ${{ secrets.CORTEX_API_KEY }} \
        #    --api-key-id ${{ secrets.CORTEX_API_KEY_ID }} \
        #    image sbom ${{ secrets.GAR_PREFIX }}/${{ secrets.GCP_PROJECT }}/${{ github.repository }}:${{ github.run_number }} \
        #    --output-file /home/code/${{ github.repository }}.${{ github.run_number }}.sbom \
        #    --fields author, binaries, license, name, purl, sourcePackage, type, version

      #- name: Archive Application Image SBOM
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: sbom-manifests
      #    path: ${{ github.repository }}.${{ github.run_number }}.sbom
      #    retention-days: 20                                                # 90 is the default

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'                # SA with access to registry and cluster

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT }}                            # gcp project name 
          install_components: 'gke-gcloud-auth-plugin'                      # for kube auth to work

      - name: Push Application Image to Registry
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}                           # gcp project name 
        run: |
          gcloud auth configure-docker ${{ secrets.GAR_PREFIX }}
          docker push ${{ secrets.GAR_PREFIX }}/${{ secrets.GCP_PROJECT }}/${{ github.repository }}:${{ github.run_number }}
      #  env:
      #    QUAY_USER: ${{ secrets.QUAY_USER }}
      #    QUAY_PW: ${{ secrets.QUAY_PW }}
      #  run: echo "docker push quay.io/mmurhamm/${{ github.repository }}:${{ github.run_number }} ..."
      #  run: |
      #    docker login quay.io -u ${{ secrets.QUAY_USER }} -p ${{ secrets.QUAY_PW }}
      #    docker push quay.io/mmurhamm/${{ github.repository }}:${{ github.run_number }}

      - name: Deploy Application to GKE
        env:
          GCP_PROJECT: ${{ secrets.GCP_PROJECT }}                           # gcp project name 
       #   GCP_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
       #   QUAY_USER: ${{ secrets.QUAY_USER }}
       #   QUAY_PW: ${{ secrets.QUAY_PW }}          
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER }} --zone ${{ secrets.GKE_ZONE }} --project ${{ secrets.GCP_PROJECT }}
          # gcloud auth configure-docker ${{ secrets.GAR_PREFIX }}
          helm upgrade \
          ${{ github.event.repository.name }} \
          helm \
          --install \
          --create-namespace \
          --namespace ${{ github.event.repository.name }} \
          --set image.repository=${{ secrets.GAR_PREFIX }}/${{ secrets.GCP_PROJECT }}/${{ github.repository }} \
          --set image.tag=${{ github.run_number }} \
          --set dockerConfigJson.data="$(cat ~/.docker/config.json | base64 -w 0)"
       #   --set imageCredentials.username=${{ secrets.QUAY_USER }} \
       #   --set imageCredentials.password=${{ secrets.QUAY_PW }} \
       #   --set imageCredentials.repositoryUriPrefix=quay.io \
       #   --set imageCredentials.registry=quay.io
